// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zveqdqalrtliftlogikl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp2ZXFkcWFscnRsaWZ0bG9naWtsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2NjI1MDQsImV4cCI6MjA3MzIzODUwNH0.Fhb5LjtKpBaoSeqooW-khtwoeCUfcfPG24F4xaVS0PQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});